# Generated by Django 3.0.7 on 2020-06-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisorderPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhd', models.IntegerField(default=0)),
                ('asd', models.IntegerField(default=0)),
                ('depression', models.IntegerField(default=0)),
                ('ptsd', models.IntegerField(default=0)),
                ('dyslexia', models.IntegerField(default=0)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
        ),
    ]
