# Generated by Django 3.0.7 on 2020-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_disorderpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
