# Generated by Django 3.0.7 on 2020-06-27 11:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer_creds', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('response_pos', models.CharField(max_length=500)),
                ('response_neg', models.CharField(max_length=500)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
        ),
    ]
