# Generated by Django 3.0.7 on 2020-06-27 11:50

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_toask'),
    ]

    operations = [
        migrations.AddField(
            model_name='toask',
            name='redirection',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2),
            preserve_default=False,
        ),
    ]
