# Generated by Django 3.0.7 on 2020-06-27 11:56

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_toask_belongs_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='toask',
            name='disorders_arr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)
        ),
    ]
