# Generated by Django 3.0.7 on 2020-06-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_toask_disorders_arr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toask',
            old_name='answer_creds',
            new_name='answer_cred',
        ),
    ]
