# Generated by Django 3.0.7 on 2020-06-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200627_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='computer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='literature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='maths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='moral_science',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='science',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='social_studies',
            field=models.IntegerField(default=0),
        ),
    ]
