# Generated by Django 3.0.7 on 2020-06-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200627_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='naam', max_length=50),
        ),
    ]
